[tools]
erlang = "28.0.1"
gleam = "1.11.1"
elixir = "1.18.4-otp-28"
opam = "2.3.0"
node = "latest"
bun = "latest"
coursier = "latest"
mysql = "latest"
rust = "latest"
go = "latest"
java = "temurin-17"
maven = "latest"
usage = "latest"
